### ISSUE TITLE
API for Scanning Receipts

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#12]

**Comment by Thecaprifire** [comment]
** User Story
As a developer, I want to obtain an API that can scan receipt items so that I can automate the process of extracting and updating item information from receipts.

** Acceptance Criteria
- Receipt Upload and Scan: The API should provide a function to upload and scan a receipt image or PDF.
 The upload function should support common image formats (e.g., JPEG, PNG) and PDF.
 The scan function should accurately extract item details such as name, and quantity from the receipt.
- Data Processing: The scanned data should be processed to update the item list in the database or data structure.
 The API should ensure data integrity and handle duplicate items appropriately.
 The extracted data should include item name, and quantity.
- UI Update: The API should provide a mechanism to update the UI with the scanned items.
 The UI update should reflect the new items added from the receipt scan.
 It should highlight any discrepancies or errors found during scanning.
- Testing Functionality: Developers should be able to test the scanning functionality to ensure accuracy.
 The API should include test endpoints or a sandbox environment for testing.
 The API should provide detailed logs or feedback on the scanning accuracy and any errors encountered.
