### ISSUE TITLE
API for Recipes

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#13]

**Comment by Thecaprifire** [comment]
** User Story
As a developer, I want to obtain an API that can provide probable recipes based on the items scanned from a receipt or listed in user data so that I can offer recipe suggestions to users based on their available ingredients.

** Acceptance Criteria
- Fetch Recipes Based on Items: The API should have a function to fetch recipes based on items that are listed, scanned, or enrolled in the user's data.
 The function should accept a list of items (names or IDs) as input.
 The function should return a list of recipes that use these items as ingredients.
 The response should include recipe details such as title, ingredients, instructions, and any necessary metadata (e.g., cooking time, servings).
- UI Update: The API should provide a mechanism to update the UI with the fetched recipes.
 The UI should display the recipe titles and a brief summary initially.
 Detailed views of recipes should be available, showing ingredients, steps, and other details.
- Testing Functionality: Developers should be able to test the API integration to ensure recipes are displayed correctly.
 The API should include test endpoints or a sandbox environment for testing.
 The API should provide detailed logs or feedback on the fetching process and any errors encountered.
