### ISSUE TITLE
Setup the base code for landing page.

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#26]

**Comment by Anniebooth00** [comment]
As a developer
I want to create a simple landing page with an empty div
So that I can have a base to start adding items and further develop the page.

Acceptance Criteria
WHEN I load the landing page,
THEN I see a header with a placeholder title.

WHEN I view the main content section,
THEN I see an empty div with the id "items-container" ready for adding items.

WHEN I inspect the page's styling,
THEN I see that it is styled using the UIKit CSS framework and is responsive.

WHEN I check the HTML code,
THEN I see comments explaining the structure and purpose of each section.

WHEN I validate the HTML code using W3C validation,
THEN there are no errors, and the code is well-structured.

WHEN I open the browser console,
THEN there are no errors, and the page loads correctly.

WHEN I check the version control history,
THEN I see a commit with a clear message indicating the creation of the initial landing page code.
