### ISSUE TITLE
API for Random Advice Generator

### ISSUE THREAD

**Issue by trishamasbate** [Anniebooth00/No-Waste-Grocery-Management-Dashboard#9]

**Comment by Thecaprifire** [comment]
** User Story
As a developer,
I want an API that provides random pieces of advice,
So that I can integrate it into applications to offer users inspirational or helpful advice.

** Acceptance Criteria
- Random Advice Generation:
   - When a user clicks the button with the ID adviceButton, the API should fetch and display a piece of random advice.
   - The advice should be displayed in an HTML element with the ID advice.
- Input Validation:
   - The API should not require any specific input data to provide advice.
   - The endpoint should be accessible with a simple GET request.
- Error Handling:
   - If the server encounters an error, the API should handle it gracefully.
   - The error should be logged to the console.
   - The HTML element with the ID advice should display a fallback message: "Could not fetch advice. Please try again later."
- Documentation:
   - The API should be well-documented.
   - Documentation should include:
   - Descriptions of the endpoint.
   - Example requests and responses.
   - Explanation of any parameters (if applicable).
- Security:
   - The API should implement secure practices to prevent unauthorized access.
- Performance:
   - The API should be performant and capable of handling a reasonable load of requests without significant latency.
